config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#top'
  resources :sessions, only: [:new, :create, :destroy]
  resources :loves, only: [:create, :destroy]
  resources :users do
    member do
      get :likes
    end
  end
  resources :blogs do
    post 'likes', to: 'loves#create'
    delete '/likes', to: 'loves#destroy'
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  has_many :loves, dependent: :destroy
  has_many :love_users, through: :loves, source: :user
end

app/models/love.rb
class Love < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }, on: :create
  has_many :blogs
  has_many :loves, dependent: :destroy
  has_many :Love_blogs, through: :loves, source: :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

def index
  @blogs = Blog.all.order(id: "desc")
end

def new
  if params[:back]
    @blog = Blog.new(blog_params)
  else
    @blog = Blog.new
  end
end

def create
  @blog = current_user.blogs.build(blog_params)
  if params[:back]
    render :new
  else
    if @blog.save
      ConfirmMailer.confirm_mail(@blog, current_user).deliver
      redirect_to blogs_path, notice: "Vous avez créé un blog !"
    else
      render 'new'
    end
  end
end

def show
  @love = current_user.loves.find_by(blog_id: @blog.id)
end

def edit
  if Blog.find(params[:id]).user.name == current_user.name
      @blog = Blog.find(params[:id])
    else
      redirect_to blogs_path
  end
  unless @blog.user_id == current_user.id
    redirect_to blogs_path, notice: "Non autorisé."
  end
end

def update
  if @blog.update(blog_params)
    redirect_to blogs_path, notice: 'Poste modifié par '
  else
    render 'edit'
  end
end

def destroy
  @blog.destroy
  redirect_to blogs_path, notice: 'Blog supprimé.'
end

def confirm
  @user = User.find(session[:user_id])
  @blog = Blog.new(blog_params)
  @blog.user_id = current_user.id
  render 'new' if @blog.invalid?
end

private

def blog_params
   params.require(:blog).permit(:title, :content, :image, :image_cache)
end

def set_blog
  @blog = Blog.find(params[:id])
end

def logged_in?
  unless current_user.present?
   flash[:notice] = 'Connectez-vous.'
   redirect_to new_session_path
  end
 end
end

app/controllers/loves_controller.rb
class LovesController < ApplicationController
  def create
    love = current_user.loves.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{love.blog.user.name}Le blog de S a été ajouté aux favoris"
  end

  def destroy
    love = current_user.loves.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{love.blog.user.name}Blog non blogué de M."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to blogs_path
    else
      flash[:danger] = 'Connexion Impossible'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Deconnexion'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :likes]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def likes
    @loves = User.find(current_user.id).loves.order(id: "desc")
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache )
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to blogs_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
   if action_name == 'new' || action_name == 'confirm'
     confirm_blogs_path
   elsif action_name == 'edit'
     blog_path
   end
  end
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_users_path
    elsif action_name == 'edit'
      user_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>Vous avez fais<%= @blog.errors.count %> Erreur(s)</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= form.label :image, "Image" %>
    </p>
    <p>
      <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </p>
  </div>
  <div class="blog_content">
    <p>
      <%= form.label :content %>
    </p>
    <p>
      <%= form.text_field :content, size: :"100*50" %>
    </p>
  </div>
  <p><%= form.submit "Publier"%></p>
<% end %>
<p><%= link_to "Revenir", blogs_path %></p>

app/views/blogs/confirm.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>

<main>
<h3>Confirmer votre poste !!!</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>

  <p><%= @blog.content %></p>
  <br>
  <%= form.submit "Publier" %>
  <% end %>
  <br>
<%= form_with(model: @blog, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "retourner", name: "back", class: 'botton' %>
  <%= form.submit "Non", name: 'Non'%>
<% end %>
</main>

app/views/blogs/edit.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>

<main>
  <%= render 'form' %>
</main>

app/views/blogs/index.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
    <%= link_to "Se deconnecter", session_path(current_user.id), method: :delete %>
  </div>
</header>

<main>
  <br>
  <br>
  <div class="left_box">
    <div class="share_box">
        <button class="btn profile-edit-btn" type="button"><%= link_to 'Faire Un Poste', new_blog_path %></button>
    </div>
    <% @blogs.each do |blog| %>
    <div class="main_box">
      <table>
        <tr>
          <td>
            <div class="main_box_head">
              <% if blog.user.image.file.nil? %>
                <%= image_tag 'no_profile_pic.png', class: 'contributer_img' %>
                <% else %>
                <%= image_tag blog.user.image.url, class: 'contributer_img' %>
              <% end %>
              <%= link_to "#{blog.user.name}", user_path(blog.user.id), class: 'contributer' %>
              <div class="main_box_menu">
                <%= link_to 'Voir le poste', blog_path(blog.id) %>
                <% if current_user.id == blog.user.id %>
                <%= link_to "Edite", edit_blog_path(blog.id) %>
                <%= link_to 'Supprimer', blog_path(blog.id), method: :delete ,data: { confirm: 'Voulez Vous Vraiment Supprimer ?' } %>
              </div>
            </div>
          </td>
          <% end %>
        </tr>
        <tr>
          <td>
          <% if blog.image.file.nil? %>
            <% else %>
            <%= image_tag blog.image.url, class: 'main_box_img' %>
          <% end %>
          </td>
        </tr>
        <tr>
          <td>
          <div>
            <%= image_tag "like.png", class: 'heart2_img' %>
            <%= image_tag "comment.png", class: 'comment_img' %>

           <% if @love.present? %>
             <%= link_to love_path(id: @love.id), method: :delete do %>
               <%= image_tag "save_1.png", class: 'save_img' %>
             <% end %>
             <% else %>
             <%= link_to loves_path(blog_id: blog.id), method: :post do %>
               <%= image_tag "save.png", class: 'save_img' %>
             <% end %>
           <% end %>

            <p class="comment">
              <%= link_to "#{blog.user.name}", user_path(blog.user.id), class: 'contributer' %>
              <%= blog.content %>
            </p>
            <p class="upload_date"><%= blog.user.created_at.try(:strftime,"%D") %></p>
          </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="main_box_addcomment">
              <span>Ajoutez un commentaire</span>
              <div class="add_contribute">Post</div>
            </div>
          </td>
        </tr>
      </table>
    </div>
    <br>
    <br>
    <% end %>
    <br>
  </div>
</main>

app/views/blogs/new.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>
<br>
<main>
<%= render 'form' %>
</main>

app/views/blogs/show.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>

<main>
  <% unless @blog.user_id == current_user.id %>
  <% if @love.present? %>
    <%= link_to 'Supprimer le favori', love_path(id: @love.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Préféré', loves_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<p>
  <% if @blog.image.file.nil? %>
  <% else %>
    <%= image_tag @blog.image.url %>
  <% end %>
</p>
<p>
  <%= @blog.content %>
</p>
<p class="upload_date">
  <%= @blog.user.created_at.try(:strftime,"%D") %>
</p>
  <%= link_to "Retour a l'acceuil", blogs_path %>
</main>

app/views/blogs/top.html.erb
<div class="signup_box">
  <h1>INSTAGRAM CLONE</h1><br>
    <h3>Avez-vous un compte ?</h3>
    <button class="btn profile-edit-btn" type="button"><%= link_to "Se connecter ", new_session_path, class: 'log_link' %></button><br>
</div>
<%= image_tag 'Insta.png', class: 'top_image' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projet Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <%= yield %>
  <footer class="footer">
    <p>INSTAGRAM APPLICATION CLONE 2022 BY I. GADO</p>
  </footer>
</body>
</html>

app/views/users/edit.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>

<div class="login_forms">
<%= form_with(model: @user, local: true) do |f| %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
    <p>Email: <%= @user.email %></p>
  <%= f.label :Photo_de_profil %>
<p>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
</p>
<p>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
</p><br>
  <%= f.submit "Modifier" %>
<% end %>
</div>

app/views/users/likes.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>

<main>
  <h1>Mes Favoris</h1>
    <p><%= link_to "Revenir", blogs_path %></p>
  <% @loves.each do |love| %>
  <table>
    <tr>
      <td>Posté Par <%= link_to "#{love.blog.user.name}", user_path(love.blog.user.id) %></td>
      <td><%= link_to 'Details', blog_path(love.blog.id) %></td>
    </tr>
    <tr>
      <td>
        <% if love.blog.image.file.nil? %>
          <% else %>
          <%= image_tag love.blog.image.url %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <%= love.user.created_at.try(:strftime,"%D") %>
        <%= love.blog.content %>
      </td>
    </tr>
    <tr>
      <td>
      <% @love = current_user.loves.find_by(blog_id: love.blog.id) %>
      <% if @love.present? %>
      <%= link_to 'Supprimer', love_path(id: @love.id), method: :delete %>
        <% else %>
      <%= link_to 'Favoris', loves_path(blog_id: love.blog.id), method: :post%>
      <% end %>
      </td>
    </tr>
  </table>
  <% end %>
</main>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> interdit l'enregistrement de cet @user</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="signup_box">
<%= image_tag "logo.png", class: 'insta_logo1' %>
  <p>Enregistrez Vous !<br></p>
  <div class="login_forms">
    <%= form_with(model: @user, local: true) do |f| %>
      <div>
        <%= f.label :name, 'Nom Du Compte:' %>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :email, 'Email Adress:' %>
        <%= f.email_field :email %>
      </div>
      <div>
        <%= f.label :password, 'Mot de passe :' %>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation, 'Mot de passe (confirmation) :' %>
        <%= f.password_field :password_confirmation %>
      </div><br>
          <%= f.submit "Créer un compte" %>
      <% end %>
  </div>
</div>
<div class="login_box_m">
  <span>Avez-vous un compte ?</span> <%= link_to "Se connecter ", new_session_path, class: 'login_link' %>
</div>

app/views/users/show.html.erb
<header>
  <div class="head">
    <%= link_to blogs_path do %>
      <%= image_tag "logo.png", class: 'insta_logo' %>
    <% end %>

    <span><%= image_tag "recherche.png", class: 'recherche' %>rechercher</span>
    <%= link_to "#" do %>
      <%= image_tag "home.png", class: 'icon' %>
      <%= image_tag "add.png", class: 'icon' %>
      <%= image_tag "messenger.png", class: 'icon' %>
      <%= image_tag "explore.png", class: 'icon' %>
      <%= image_tag "like.png", class: 'icon' %>
      <%= image_tag "user.png", class: 'icon' %>
    <% end %>
  </div>
</header>

<div class="signup_box">
  <h1>Profil de <%= @user.name %></h1>
  <% if current_user.id == @user.id %>
    <p><%= link_to "Edite", edit_user_path(@user.id) %></p>
  <% end %>

  <% if @user.image.file.nil? %>
    <%= image_tag 'no_profile_pic_big.png', class: 'profile_img' %>
    <% else %>
    <%= image_tag @user.image.url, class: 'profile_img' %>
  <% end %><br><br>

  <% if current_user.id == @user.id %>
    <p><%= link_to "Postes Favoris", likes_user_path(current_user.id) %></p>
    <p><%= link_to "Revenir", blogs_path %></p>
    <p><%= link_to "Se deconnecter", session_path(current_user.id), method: :delete %></p>
  <% end %>
</div>